version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.cpu
    container_name: code-gen-backend
    environment:
      - HF_MODEL=${HF_MODEL:-deepseek-ai/deepseek-coder-6.7b-instruct-awq}
      - HF_TOKEN=${HF_TOKEN}
      - DEVICE=${DEVICE:-cpu}
      - QUANTIZATION=${QUANTIZATION:-4bit}
      - MAX_LENGTH=${MAX_LENGTH:-2048}
      - TEMPERATURE=${TEMPERATURE:-0.7}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - hf-cache:/root/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 120s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: code-gen-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  hf-cache:
    driver: local
